http
{
		server {
	
		listen  8080;

		client_max_body_size  1048576;

		allow_method GET;

		server_name  localhost:8080;
		
		root www/;
		index index.html;		
		error_page_404  www/errors/404.html;
		error_page_500  www/errors/500.html;
	}
}